### ISSUE TITLE
Find a way *to log* in a personal space.

### ISSUE THREAD

**Issue by grammaton** [SMERM/EMUForm#10]
A `login` interface to grant personal access on submission form and file upload.    
A *ready to shot* option could be:    
https://github.com/mohitjain/social-login-in-rails.git

**Comment by nicb** [comment]
This means that we also have to link the `work` table and the future `author` table to a `user` table. What is the relationship between a `user` and an `author`? one to one?

Or rather: we link the work submission to a user. And the work is linked to one or more `authors`. So we don't have to have a connection. Agreed?

**Comment by nicb** [comment]
Using [your solution](https://github.com/mohitjain/social-login-in-rails.git) requires integrating that `rails` app into ours. Requires some attention. I assign it to myself :-)

**Comment by nicb** [comment]
Mind you, we also need to build roles around users. We are the staff (i.e. admin), while they are complete lusers.

**Comment by grammaton** [comment]
it could be  *one to one* `author`to `user` **or** (option) the user only a submitter. This will be the best option. But for this stage one half of that thing is enough.

For roles… at this time staff group is not required. We could introduce staffers later. Could we?

**Comment by nicb** [comment]
> For roles… at this time staff group is not required. We could introduce staffers later. Could we?

Yes. Anything can be introduced *later*. You are right.

**Comment by nicb** [comment]
>> For roles… at this time staff group is not required. We could introduce staffers later. Could we?
>
>Yes. Anything can be introduced later. You are right.

Huh, in fact, no. We need to have roles to have proper views etc. We might as well implement them right away.
