### ISSUE TITLE
add uploading of directories

### ISSUE THREAD

**Issue by nicb** [SMERM/EMUForm#3]
directories should be uploaded as such, or perhaps zipped and then uploaded?

**Comment by grammaton** [comment]
Not zipped. Uncompressed folders are readable from web and mobile devices.

**Comment by nicb** [comment]
Is this a feature or rather a security hazard?

**Comment by grammaton** [comment]
When multiple files are zipped and upload as big-one there are more possibilities to fail.
On multiple file uploader like one we are testing, each file have proper upload time and a possible failure story.

**Comment by nicb** [comment]
Yes. You are right. We keep it this way. Starting to work on it on my branch now.

**Comment by nicb** [comment]
Ok. Done it this way. As of now there's no way to upload a tree, just a flat hierarchy of files. Closing this issue.
