### ISSUE TITLE
There is a stray 'sign out' while adding a new work.

### ISSUE THREAD

**Issue by nicb** [SMERM/EMUForm#48]

**Comment by nicb** [comment]
Actually, there's a `sign out` button everywhere. While this is correct (you should be able to `sign out` wherever you want), it should not be at the bottom of the page, me thinks. It should probably be on the top right, while the bottom of the page should always lead to the index of works for each user.

**Comment by grammaton** [comment]
ok… I've arranged all with big buttons, easy to push also on tablet and smartphone. 
at the bottom there is the *form nav bar* with **list of works** and **sign out** buttons.
for each page we have a small  edit button above the *form nav bar*.

DONE!
